### ISSUE TITLE
Issue with storm -> storms 

### ISSUE THREAD

**Issue by calipfleger** [nbissonnette123/issues-lab#1]
I think the data that you are referencing should be `summary(storms)` 

https://github.com/nbissonnette123/issues-lab/blob/7b5f681fd1fd8fac4e153d9440bd07a772884519/got_issues.Rmd#L18

**Comment by nbissonnette123** [comment]
I have corrected this issue by making it storms.

**Comment by nbissonnette123** [comment]
I have corrected this issue by making it storms.
