### ISSUE TITLE
Issue with X label title

### ISSUE THREAD

**Issue by calipfleger** [nbissonnette123/issues-lab#3]
I recommend that the title for the x axis is "Storm Category" 

https://github.com/nbissonnette123/issues-lab/blob/7b5f681fd1fd8fac4e153d9440bd07a772884519/got_issues.Rmd#L34

**Comment by nbissonnette123** [comment]
Thanks Cali, I have corrected this by relabeling it "storm Category

**Comment by nbissonnette123** [comment]
Thanks Cali, I have corrected this by relabeling it "storm Category
